# Generated by Django 3.0.5 on 2020-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20200423_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='name', max_length=40),
        ),
    ]
